# Generated by Django 4.0.5 on 2022-06-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_event_tickets_event_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='event',
            name='tickets',
            field=models.ManyToManyField(related_name='event_tickets', to='events.ticket'),
        ),
    ]
