# Generated by Django 4.0.5 on 2022-06-14 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_event_slug_alter_event_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tickets',
        ),
        migrations.AddField(
            model_name='event',
            name='tickets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.ticket'),
        ),
    ]
