# Generated by Django 4.0.5 on 2022-06-14 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_event_tickets_event_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tickets',
        ),
        migrations.AddField(
            model_name='event',
            name='tickets',
            field=models.ManyToManyField(related_name='events', to='events.ticket'),
        ),
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tickets', to='events.event')),
                ('tickets', models.ManyToManyField(related_name='event_tickets', to='events.ticket')),
            ],
        ),
    ]
