# Generated by Django 4.0.5 on 2022-06-14 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_event_tickets_event_tickets_ticketevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tickets',
        ),
    ]
