# Generated by Django 4.0.5 on 2022-06-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_remove_event_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tickets',
            field=models.ManyToManyField(related_name='events', to='events.ticket'),
        ),
        migrations.DeleteModel(
            name='TicketEvent',
        ),
    ]
