# Generated by Django 4.0.5 on 2022-06-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_event_tickets_delete_ticketevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='currency',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
